name: NPM Test
on: [push, pull_request]

jobs:
  npmtest:
    name: npm run test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12.x]

      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
        env:
          CI: true
